import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { fetchBrandInfo } from '~/utils/api'
import { getHostname } from '~/utils/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const hostname = getHostname()
  console.log('hostname', hostname)
  const { data: brandInfo } = await fetchBrandInfo(hostname)
  console.log('brandInfo', brandInfo)
  // const response = await fetch(`https://dummy.spa-works.jp/api/brands/${hostname}`)
  // const data = await response.json()
  // console.log('data', data)

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
